@EchoLingo_HostAddress = http://localhost:5284

###
POST https://localhost:7207/api/translate
Content-Type: application/json

{
  "text": "I enjoy learning new languages.",
  "targetLanguage": "sv"
}
